rss:
  channel:
    atom-link:
      href: ${RSS_CHANNEL_ATOM_LINK_HREF}
    title: ${RSS_CHANNEL_TITLE}
    description: ${RSS_CHANNEL_DESCRIPTION}
    link: ${RSS_CHANNEL_LINK}
    image:
      url: ${RSS_CHANNEL_IMAGE_URL:}
      width: ${RSS_CHANNEL_IMAGE_WIDTH:}
      height: ${RSS_CHANNEL_IMAGE_HEIGHT:}
      title: ${RSS_CHANNEL_IMAGE_TITLE:}
      link: ${RSS_CHANNEL_IMAGE_LINK:}
      description: ${RSS_CHANNEL_IMAGE_DESCRIPTION:}
item-factory:
  guid: ${ITEM_FACTORY_GUID:}
  link: ${ITEM_FACTORY_LINK}
  title: ${ITEM_FACTORY_TITLE}
  description: ${ITEM_FACTORY_DESCRIPTION}
  author: ${ITEM_FACTORY_AUTHOR:}
  category: ${ITEM_FACTORY_CATEGORY:}
  enclosure: ${ITEM_FACTORY_ENCLOSURE:}
  source: ${ITEM_FACTORY_SOURCE:}
  pub-date: ${ITEM_FACTORY_PUB_DATE:<</created_at>>}
strapi:
  model: ${STRAPI_MODEL}
  collection-url: ${STRAPI_COLLECTION_URL}
events:
  username: ${EVENTS_USERNAME:}
  password: ${EVENTS_PASSWORD:}